name: sights_to_see
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  cupertino_icons: ^1.0.8
  firebase_data_connect: ^0.1.0
  sqflite: ^2.2.6
  path: ^1.8.3
  uuid: ^3.0.6
  logging: ^1.1.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/one.jpg
