// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7kLS2C_b6PgCMr_dau9ePBPAVjs1mPWs',
    appId: '1:56731933210:web:a9c9c5e00f85cd12a68fa3',
    messagingSenderId: '56731933210',
    projectId: 'sight-to-see',
    authDomain: 'sight-to-see.firebaseapp.com',
    storageBucket: 'sight-to-see.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4xeQQHXzMBm_dMC7Sa96RPCMr41i4VlQ',
    appId: '1:56731933210:android:4a04cd713d7b276ba68fa3',
    messagingSenderId: '56731933210',
    projectId: 'sight-to-see',
    storageBucket: 'sight-to-see.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzlgVim7iI1VBecZZYYmO9P98f8_sXpJE',
    appId: '1:56731933210:ios:78684741c512416ca68fa3',
    messagingSenderId: '56731933210',
    projectId: 'sight-to-see',
    storageBucket: 'sight-to-see.firebasestorage.app',
    iosBundleId: 'com.example.sightsToSee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzlgVim7iI1VBecZZYYmO9P98f8_sXpJE',
    appId: '1:56731933210:ios:78684741c512416ca68fa3',
    messagingSenderId: '56731933210',
    projectId: 'sight-to-see',
    storageBucket: 'sight-to-see.firebasestorage.app',
    iosBundleId: 'com.example.sightsToSee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7kLS2C_b6PgCMr_dau9ePBPAVjs1mPWs',
    appId: '1:56731933210:web:42789c2e0bf20976a68fa3',
    messagingSenderId: '56731933210',
    projectId: 'sight-to-see',
    authDomain: 'sight-to-see.firebaseapp.com',
    storageBucket: 'sight-to-see.firebasestorage.app',
  );
}
